## |------------------------------------------------------------------------| #
# source_silent ----
## |------------------------------------------------------------------------| #

#' Silently source R script with optional message and warning suppression
#'
#' This function sources an R script file with options to suppress messages
#' and/or warnings. It is useful for running scripts that generate a lot of
#' console output that is not needed.
#' @name source_silent
#' @param file Character. Path of the file to be sourced.
#' @param messages Logical. If `TRUE` (default), messages generated by the
#'   script are shown. If `FALSE`, messages are suppressed.
#' @param warnings Logical. If `TRUE` (default), warnings generated by the
#'   script are shown. If `FALSE`, warnings are suppressed.
#' @param ... Additional arguments passed to the [source] function.
#' @author Ahmed El-Gabbas
#' @return It is used for its side effect of sourcing a file with optional
#'   suppression of messages and warnings.
#' @export

source_silent <- function(file, messages = TRUE, warnings = TRUE, ...) {

  if (is.null(file)) {
    ecokit::stop_ctx("`file` cannot be NULL", file = file)
  }

  if (!file.exists(file)) {
    ecokit::stop_ctx("`file` does not exist", file = file)
  }

  if (messages && warnings) {
    file %>%
      source(...) %>%
      utils::capture.output(file = nullfile())
  }

  if (isFALSE(messages) && isFALSE(warnings)) {
    file %>%
      source(...) %>%
      utils::capture.output(file = nullfile()) %>%
      suppressMessages() %>%
      suppressWarnings()
  }

  if (messages && isFALSE(warnings)) {
    file %>%
      source(...) %>%
      utils::capture.output(file = nullfile()) %>%
      suppressWarnings()
  }

  if (isFALSE(messages) && warnings) {
    file %>%
      source(...) %>%
      utils::capture.output(file = nullfile()) %>%
      suppressMessages()
  }

  return(invisible(NULL))

}
